/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admineventos.interfaceEvento;

import admineventos.gravarDadosEvento;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ISMAE
 */
public class adcEventoInterface extends javax.swing.JInternalFrame {

    /**
     * Creates new form adcEventoInterface
     */
    public adcEventoInterface() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNomeEvento = new javax.swing.JTextField();
        campoIdEvento = new javax.swing.JTextField();
        campoDescricaoEvento = new javax.swing.JTextField();
        campoValorEvento = new javax.swing.JTextField();
        campoIngressoDispoEvento = new javax.swing.JTextField();
        campoIngressoVendidos = new javax.swing.JTextField();
        campoPessoasCadastrada = new javax.swing.JTextField();
        campoDataEvento = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Cadastro de eventos");

        jLabel1.setText("Nome do evento:");

        jLabel2.setText("ID do evento:");

        jLabel3.setText("Descrição do evento:");

        jLabel4.setText("Valor do ingresso:");

        jLabel5.setText("Ingressos disponivel:");

        jLabel6.setText("Ingressos vendidos:");

        jLabel7.setText("Nº de pessoas cadastrada:");

        jLabel8.setText("Data do evento: (ANO-MES-DIA)");

        campoNomeEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeEventoActionPerformed(evt);
            }
        });

        campoValorEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorEventoActionPerformed(evt);
            }
        });

        campoIngressoDispoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIngressoDispoEventoActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(botaoSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNomeEvento)
                                .addComponent(campoDescricaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(campoIngressoDispoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoIngressoVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(campoPessoasCadastrada, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(campoDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoValorEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(campoNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIdEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(campoDescricaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIngressoDispoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoValorEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoIngressoVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPessoasCadastrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvar)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeEventoActionPerformed

    private void campoValorEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorEventoActionPerformed

    private void campoIngressoDispoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIngressoDispoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIngressoDispoEventoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        
        String confere = "teste";
        boolean confereID, confereValor, confereDisponivel, confereVendidos, confereCadas, confereData;
        gravarDadosEvento gravar = new gravarDadosEvento();
        adcEventoInterface cadastroEvento = new adcEventoInterface();
        
        //Passa os dados recebido para o metodo de cadastro
        gravar.setNomeEvento(campoNomeEvento.getText());
        gravar.setIdEvento(campoIdEvento.getText());
        gravar.setDescricaoEvento(campoDescricaoEvento.getText());
        gravar.setValorIngressoEvento(campoValorEvento.getText());
        gravar.setTotalIngrecosEvento(campoIngressoDispoEvento.getText());
        gravar.setIngrecosVendidoEvento(campoIngressoVendidos.getText());
        gravar.setPessoasCadastradaEvento(campoPessoasCadastrada.getText());
        gravar.setDataEvento(campoDataEvento.getText());        
        
        
        //Faz tratamento de erros, verificando se os datos recebidos são int, float
        confereID = gravar.verificaInt(campoIdEvento.getText());
        if(confereID == false){
            JOptionPane.showMessageDialog(rootPane,"ID invalida!");
        }
        confereValor = gravar.verificaFloat(campoValorEvento.getText());
        if(confereValor == false){
            JOptionPane.showMessageDialog(rootPane,"Valor invalido!");
        }
        confereDisponivel = gravar.verificaInt(campoIngressoDispoEvento.getText());
        if(confereDisponivel == false){
            JOptionPane.showMessageDialog(rootPane,"Quantidade disponivel invalida!");
        }
        confereVendidos = gravar.verificaInt(campoIngressoVendidos.getText());
        if(confereVendidos == false){
            JOptionPane.showMessageDialog(rootPane,"Quantidade vendidos invalido!");
        }
        confereCadas = gravar.verificaInt(campoPessoasCadastrada.getText());
        if(confereCadas == false){
            JOptionPane.showMessageDialog(rootPane,"Numero de pessoas cadastradas invalido!");
        }
        confereData = gravar.verificaData(campoDataEvento.getText());
        if(confereData == false){
            JOptionPane.showMessageDialog(rootPane,"Data invalida!");
        }
        //#############################################################
        
        
        if(confereID == true && confereValor == true 
           && confereDisponivel == true && confereVendidos == true 
           && confereCadas == true && confereData == true){
            try {
                confere = gravar.gravarDados();
            } catch (IOException ex) {
                Logger.getLogger(adcEventoInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane, confere);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Alguns dados estão em um formato invalido, verifique e tente novamente.");
        }
        cadastroEvento.setVisible(false);
    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoDataEvento;
    private javax.swing.JTextField campoDescricaoEvento;
    private javax.swing.JTextField campoIdEvento;
    private javax.swing.JTextField campoIngressoDispoEvento;
    private javax.swing.JTextField campoIngressoVendidos;
    private javax.swing.JTextField campoNomeEvento;
    private javax.swing.JTextField campoPessoasCadastrada;
    private javax.swing.JTextField campoValorEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
